function getVisitedCountries() {
  var countryInfo = getCountryInfo()
  return Object.keys(countryInfo).filter(country => countryInfo[country].visited)
}

function getCountryInfo () {
  return {
    'ZWE': {
      countryName: 'Zimbabwe',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'zw',
      },
    'ZMB': {
      countryName: 'Zambia',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'zm',
      },
    'ZAF': {
      countryName: 'South Africa',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'za',
      },
    'UGA': {
      countryName: 'Uganda',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ug',
      },
    'TZA': {
      countryName: 'Tanzania',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'tz',
      },
    'TUN': {
      countryName: 'Tunisia',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'tn',
      },
    'TGO': {
      countryName: 'Togo',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'tg',
      },
    'TCD': {
      countryName: 'Chad',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'td',
      },
    'SWZ': {
      countryName: 'Eswatini',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'sz',
      },
    'SSD': {
      countryName: 'South Sudan',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ss',
      },
    'SOM': {
      countryName: 'Somalia',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'so',
      },
    'somaliland': {
      countryName: 'Somaliland',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: '_Somaliland',
      },
    'SLE': {
      countryName: 'Sierra Leone',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'sl',
      },
    'SHN': {
      countryName: 'Saint Helena',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'sh',
      },
    'SEN': {
      countryName: 'Senegal',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'sn',
      },
    'SDN': {
      countryName: 'Sudan',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'sd',
      },
    'RWA': {
      countryName: 'Rwanda',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'rw',
      },
    'REU': {
      countryName: 'Réunion',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 're',
      },
    'NGA': {
      countryName: 'Nigeria',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ng',
      },
    'NER': {
      countryName: 'Niger',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ne',
      },
    'NAM': {
      countryName: 'Namibia',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'na',
      },
    'MYT': {
      countryName: 'Mayotte',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'yt',
      },
    'MWI': {
      countryName: 'Malawi',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'mw',
      },
    'MUS': {
      countryName: 'Mauritius',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'mu',
      },
    'MRT': {
      countryName: 'Mauritania',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'mr',
      },
    'MOZ': {
      countryName: 'Mozambique',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'mz',
      },
    'MLI': {
      countryName: 'Mali',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ml',
      },
    'MDG': {
      countryName: 'Madagascar',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'mg',
      },
    'MAR': {
      countryName: 'Morocco',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'ma',
      },
    'LSO': {
      countryName: 'Lesotho',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ls',
      },
    'LBY': {
      countryName: 'Libya',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ly',
      },
    'LBR': {
      countryName: 'Liberia',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'lr',
      },
    'KEN': {
      countryName: 'Kenya',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'ke',
      },
    'GNQ': {
      countryName: 'Equatorial Guinea',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'gq',
      },
    'GNB': {
      countryName: 'Guinea-Bissau',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'gw',
      },
    'GMB': {
      countryName: 'Gambia',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'gm',
      },
    'GIN': {
      countryName: 'Guinea',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'gn',
      },
    'GHA': {
      countryName: 'Ghana',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'gh',
      },
    'GAB': {
      countryName: 'Gabon',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ga',
      },
    'ETH': {
      countryName: 'Ethiopia',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'et',
      },
    'ESH': {
      countryName: 'Western Sahara',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'eh',
    },
    'ERI': {
      countryName: 'Eritrea',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'er',
    },
    'EGY': {
      countryName: 'Egypt',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'eg',
    },
    'DZA': {
      countryName: 'Algeria',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'dz',
    },
    'DJI': {
      countryName: 'Djibouti',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'dj',
    },
    'CPV': {
      countryName: 'Cabo Verde',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'cv',
    },
    'COM': {
      countryName: 'Comoros',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'km',
    },
    'COG': {
      countryName: 'Republic of the Congo',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'cg',
    },
    'COD': {
      countryName: 'Democratic Republic of the Congo',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'cd',
    },
    'CMR': {
      countryName: 'Cameroon',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'cm',
    },
    'CIV': {
      countryName: 'Côte d\'Ivoire',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ci',
    },
    'CAF': {
      countryName: 'Central African Republic',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'cf',
    },
    'BWA': {
      countryName: 'Botswana',
      fillKey: 'africa',
      visited: true,
      lived: false,
      flagName: 'bw',
    },
    'BFA': {
      countryName: 'Burkina Faso',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'bf',
    },
    'BEN': {
      countryName: 'Benin',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'bj',
    },
    'BDI': {
      countryName: 'Burundi',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'bi',
    },
    'AGO': {
      countryName: 'Angola',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'ao',
    },

    'YEM': {
      countryName: 'Yemen',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'ye',
    },
    'VNM': {
      countryName: 'Vietnam',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'vn',
    },
    'UZB': {
      countryName: 'Uzbekistan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'uz',
    },
    'TWN': {
      countryName: 'Taiwan',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'tw',
    },
    'TUR': {
      countryName: 'Türkiye',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'tr',
    },
    'TLS': {
      countryName: 'Timor-Leste',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'tl',
    },
    'TKM': {
      countryName: 'Turkmenistan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'tm',
    },
    'TJK': {
      countryName: 'Tajikistan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'tj',
    },
    'THA': {
      countryName: 'Thailand',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'th',
    },
    'SYR': {
      countryName: 'Syria',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'sy',
    },
    'SYC': {
      countryName: 'Seychelles',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'sc',
    },
    'SGP': {
      countryName: 'Singapore',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'sg',
    },
    'SAU': {
      countryName: 'Saudi Arabia',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'sa',
    },
    'RUS': {
      countryName: 'Russia',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'ru',
    },
    'QAT': {
      countryName: 'Qatar',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'qa',
    },
    'PSE': {
      countryName: 'Palestine',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'ps',
    },
    'PRK': {
      countryName: 'North Korea',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'kp',
    },
    'PHL': {
      countryName: 'Philippines',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'ph',
    },
    'PAK': {
      countryName: 'Pakistan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'pk',
    },
    'OMN': {
      countryName: 'Oman',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'om',
    },
    'NPL': {
      countryName: 'Nepal',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'np',
    },
    'MYS': {
      countryName: 'Malaysia',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'my',
    },
    'MNG': {
      countryName: 'Mongolia',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'mn',
    },
    'MMR': {
      countryName: 'Myanmar',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'mm',
    },
    'MDV': {
      countryName: 'Maldives',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'mv',
    },
    'MAC': {
      countryName: 'Macao',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'mo',
    },
    'LKA': {
      countryName: 'Sri Lanka',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'lk',
    },
    'LBN': {
      countryName: 'Lebanon',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'lb',
    },
    'LAO': {
      countryName: 'Laos',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'la',
    },
    'KWT': {
      countryName: 'Kuwait',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'kw',
    },
    'KOR': {
      countryName: 'South Korea',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'kr',
    },
    'KHM': {
      countryName: 'Cambodia',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'kh',
    },
    'KGZ': {
      countryName: 'Kyrgyzstan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'kg',
    },
    'KAZ': {
      countryName: 'Kazakhstan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'kz',
    },
    'JPN': {
      countryName: 'Japan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'jp',
    },
    'JOR': {
      countryName: 'Jordan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'jo',
    },
    'ISR': {
      countryName: 'Israel',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'il',
    },
    'IRQ': {
      countryName: 'Iraq',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'iq',
    },
    'IRN': {
      countryName: 'Iran',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'ir',
    },
    'IOT': {
      countryName: 'British Indian Ocean Territory',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'io',
    },
    'IND': {
      countryName: 'India',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'in',
    },
    'IDN': {
      countryName: 'Indonesia',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'id',
    },
    'HKG': {
      countryName: 'Hong Kong',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'hk',
    },
    'CXR': {
      countryName: 'Christmas Island',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'ck',
    },
    'CHN': {
      countryName: 'China',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'cn',
    },
    'CCK': {
      countryName: 'Cocos Islands',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'cc',
    },
    'BTN': {
      countryName: 'Bhutan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'bt',
    },
    'BRN': {
      countryName: 'Brunei Darussalam',
      fillKey: 'asia',
      visited: true,
      lived: false,
      flagName: 'bn',
    },
    'BHR': {
      countryName: 'Bahrain',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'bh',
    },
    'BGD': {
      countryName: 'Bangladesh',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'bd',
    },
    'AZE': {
      countryName: 'Azerbaijan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'az',
    },
    'ARM': {
      countryName: 'Armenia',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'am',
    },
    'ARE': {
      countryName: 'United Arab Emirates',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'ae',
    },
    'AFG': {
      countryName: 'Afghanistan',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'af',
    },

    'GEO': {
      countryName: 'Georgia',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'ge',
    },
    'CYP': {
      countryName: 'Cyprus',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: 'cy',
    },
    'northern_cyprus': {
      countryName: 'Northern Cyprus',
      fillKey: 'asia',
      visited: false,
      lived: false,
      flagName: '._Northern_Cyprus',
    },
    
    'VAT': {
      countryName: 'Vatican City',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'va',
    },
    'UKR': {
      countryName: 'Ukraine',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'ua',
    },
    'SWE': {
      countryName: 'Sweden',
      fillKey: 'europe',
      visited: true,
      lived: true,
      flagName: 'se',
    },
    'SVN': {
      countryName: 'Slovenia',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'si',
    },
    'SVK': {
      countryName: 'Slovakia',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'sk',
    },
    'SRB': {
      countryName: 'Serbia',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'rs',
    },
    'SMR': {
      countryName: 'San Marino',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'sm',
    },
    'SJM': {
      countryName: 'Svalbard',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'sj',
    },
    'ROU': {
      countryName: 'Romania',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'ro',
    },
    'PRT': {
      countryName: 'Portugal',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'pt',
    },
    'POL': {
      countryName: 'Poland',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'pl',
    },
    'NOR': {
      countryName: 'Norway',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'no',
    },
    'NLD': {
      countryName: 'Netherlands',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'nl',
    },
    'MNE': {
      countryName: 'Montenegro',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'me',
    },
    'MLT': {
      countryName: 'Malta',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'mt',
    },
    'MKD': {
      countryName: 'Macedonia',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'mk',
    },
    'MDA': {
      countryName: 'Moldova',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'md',
    },
    'MCO': {
      countryName: 'Monaco',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'mc',
    },
    'LVA': {
      countryName: 'Latvia',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'lv',
    },
    'LUX': {
      countryName: 'Luxembourg',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'lu',
    },
    'LTU': {
      countryName: 'Lithuania',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'lt',
    },
    'LIE': {
      countryName: 'Liechtenstein',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'li',
    },
    'JEY': {
      countryName: 'Jersey',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'je',
    },
    'ITA': {
      countryName: 'Italy',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'it',
    },
    'ISL': {
      countryName: 'Iceland',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'is',
    },
    'IRL': {
      countryName: 'Ireland',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'ie',
    },
    'IMN': {
      countryName: 'Isle of Man',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'im',
    },
    'HUN': {
      countryName: 'Hungary',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'hu',
    },
    'HRV': {
      countryName: 'Croatia',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'hr',
    },
    'GRC': {
      countryName: 'Greece',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'gr',
    },
    'GIB': {
      countryName: 'Gibraltar',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'gi',
    },
    'GGY': {
      countryName: 'Guernsey',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'gg',
    },
    'GBR': {
      countryName: 'United Kingdom',
      fillKey: 'europe',
      visited: true,
      lived: true,
      flagName: 'gb',
    },
    'FRO': {
      countryName: 'Faroe Islands',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'fo',
    },
    'FRA': {
      countryName: 'France',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'fr',
    },
    'FIN': {
      countryName: 'Finland',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'fi',
    },
    'EST': {
      countryName: 'Estonia',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'ee',
    },
    'ESP': {
      countryName: 'Spain',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'es',
    },
    'DNK': {
      countryName: 'Denmark',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'dk',
    },
    'DEU': {
      countryName: 'Germany',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'de',
    },
    'CZE': {
      countryName: 'Czechia',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'cz',
    },
    'ALA': {
      countryName: 'Åland Islands',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'ax',
    },
    'ALB': {
      countryName: 'Albania',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'al',
    },
    'AND': {
      countryName: 'Andorra',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'ad',
    },
    'AUT': {
      countryName: 'Austria',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'at',
    },
    'BEL': {
      countryName: 'Belgium',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'be',
    },
    'BGR': {
      countryName: 'Bulgaria',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'bg',
    },
    'BIH': {
      countryName: 'Bosnia and Herzegovina',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'ba',
    },
    'BLR': {
      countryName: 'Belarus',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'by',
    },
    'CHE': {
      countryName: 'Switzerland',
      fillKey: 'europe',
      visited: true,
      lived: false,
      flagName: 'ch',
    },
    'kosovo': {
      countryName: 'Kosovo',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: '_Kosovo',
    },
    'EUR_RUS': {
      countryName: 'Russia',
      fillKey: 'europe',
      visited: false,
      lived: false,
      flagName: 'ru',
    },

    'USA': {
      countryName: 'United States',
      fillKey: 'northamerica',
      visited: true,
      lived: true,
      flagName: 'us',
    },
    'MEX': {
      countryName: 'Mexico',
      fillKey: 'northamerica',
      visited: true,
      lived: false,
      flagName: 'mx',
    },
    'CAN': {
      countryName: 'Canada',
      fillKey: 'northamerica',
      visited: true,
      lived: true,
      flagName: 'ca',
    },
    'GTM': {
      countryName: 'Guatemala',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'gt',
    },
    'HND': {
      countryName: 'Honduras',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'hn',
    },
    'GRL': {
      countryName: 'Greenland',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'gl',
    },
    'SLV': {
      countryName: 'El Salvador',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'sv',
    },
    'NIC': {
      countryName: 'Nicaragua',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'ni',
    },
    'CRI': {
      countryName: 'Costa Rica',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'cr',
    },
    'DMA': {
      countryName: 'Dominica',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'dm',
    },
    'DOM': {
      countryName: 'Dominican Republic',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'do',
    },
    'CUB': {
      countryName: 'Cuba',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'cu',
    },
    'HTI': {
      countryName: 'Haiti',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'ht',
    },
    'PRI': {
      countryName: 'Puerto Rico',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'pr',
    },
    'TTO': {
      countryName: 'Trinidad and Tobago',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'tt',
    },
    'VGB': {
      countryName: 'British Virgin Islands',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'vg',
    },
    'VIR': {
      countryName: 'US Virgin Islands',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'vi',
    },
    'JAM': {
      countryName: 'Jamaica',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'jm',
    },
    'PAN': {
      countryName: 'Panama',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'pa',
    },
    'VCT': {
      countryName: 'Saint Vincent and the Grenadines',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'vc',
    },
    'UMI': {
      countryName: 'United States Minor Outlying Islands',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'um',
    },
    'TCA': {
      countryName: 'Turks and Caicos Islands',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'tc',
    },
    'SXM': {
      countryName: 'Sint Maarten (Dutch Part)',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'sx',
    },
    'STP': {
      countryName: 'Sao Tome and Principe',
      fillKey: 'africa',
      visited: false,
      lived: false,
      flagName: 'st',
    },
    'SPM': {
      countryName: 'Saint Pierre and Miquelon',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'pm',
    },
    'MTQ': {
      countryName: 'Martinique',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'mq',
    },
    'MSR': {
      countryName: 'Montserrat',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'ms',
    },
    'MAF': {
      countryName: 'Saint Martin (French part)',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'mf',
    },
    'LCA': {
      countryName: 'Saint Lucia',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'lc',
    },
    'KNA': {
      countryName: 'Saint Kitts and Nevis',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'kn',
    },
    'GRD': {
      countryName: 'Grenada',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'gd',
    },
    'GLP': {
      countryName: 'Guadeloupe',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'gp',
    },
    'CYM': {
      countryName: 'Cayman Islands',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'ky',
    },
    'BRB': {
      countryName: 'Barbados',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'bb',
    },
    'BMU': {
      countryName: 'Bermuda',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'bm',
    },
    'BLZ': {
      countryName: 'Belize',
      fillKey: 'northamerica',
      visited: false,
      lived: false,
      flagName: 'bz',
    },
    'BLM': {
      countryName: 'Saint Barthélemy',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'bl',
    },
    'BHS': {
      countryName: 'Bahamas',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'bs',
    },
    'BES': {
      countryName: 'Bonaire, Sint Eustatius and Saba',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'bq',
    },
    'ATG': {
      countryName: 'Antigua and Barbuda',
      fillKey: 'caribbean',
      visited: true,
      lived: false,
      flagName: 'ag',
    },
    'AIA': {
      countryName: 'Anguilla',
      fillKey: 'caribbean',
      visited: false,
      lived: false,
      flagName: 'ai',
    },

    'VEN': {
      countryName: 'Venezuela',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 've',
    },
    'GUY': {
      countryName: 'Guyana',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'gy',
    },
    'SUR': {
      countryName: 'Suriname',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'sr',
    },
    'GUF': {
      countryName: 'French Guiana',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'gf',
    },
    'BRA': {
      countryName: 'Brazil',
      fillKey: 'southamerica',
      visited: true,
      lived: false,
      flagName: 'br',
    },
    'URY': {
      countryName: 'Uruguay',
      fillKey: 'southamerica',
      visited: true,
      lived: false,
      flagName: 'uy',
    },
    'PRY': {
      countryName: 'Paraguay',
      fillKey: 'southamerica',
      visited: true,
      lived: false,
      flagName: 'py',
    },
    'PER': {
      countryName: 'Peru',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'pe',
    },
    'ABW': {
      countryName: 'Aruba',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'aw',
    },
    'FLK': {
      countryName: 'Falkland Islands',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'fk',
    },
    'ECU': {
      countryName: 'Ecuador',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'ec',
    },
    'CUW': {
      countryName: 'Curaçao',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'cw',
    },
    'COL': {
      countryName: 'Colombia',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'co',
    },
    'CHL': {
      countryName: 'Chile',
      fillKey: 'southamerica',
      visited: true,
      lived: false,
      flagName: 'cl',
    },
    'BOL': {
      countryName: 'Bolivia',
      fillKey: 'southamerica',
      visited: false,
      lived: false,
      flagName: 'bo',
    },
    'ARG': {
      countryName: 'Argentina',
      fillKey: 'southamerica',
      visited: true,
      lived: false,
      flagName: 'ar',
    },

    'AUS': {
      countryName: 'Australia',
      fillKey: 'oceania',
      visited: true,
      lived: false,
      flagName: 'au',
    },
    'NZL': {
      countryName: 'New Zealand',
      fillKey: 'oceania',
      visited: true,
      lived: false,
      flagName: 'nz',
    },
    'WSM': {
      countryName: 'Samoa',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'ws',
    },
    'TON': {
      countryName: 'Tonga',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'to',
    },
    'SLB': {
      countryName: 'Solomon Islands',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'sb',
    },
    'FJI': {
      countryName: 'Fiji',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'fj',
    },
    'VUT': {
      countryName: 'Vanuatu',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'vu',
    },
    'TUV': {
      countryName: 'Tuvalu',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'tv',
    },
    'TKL': {
      countryName: 'Tokelau',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'tk',
    },
    'PYF': {
      countryName: 'French Polynesia',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'pf',
    },
    'PNG': {
      countryName: 'Papua New Guinea',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'pg',
    },
    'PLW': {
      countryName: 'Palau',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'pw',
    },
    'PCN': {
      countryName: 'Pitcairn',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'pn',
    },
    'WLF': {
      countryName: 'Wallis and Futuna',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'wf',
    },
    'NRU': {
      countryName: 'Nauru',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'nr',
    },
    'NIU': {
      countryName: 'Niue',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'nu',
    },
    'NFK': {
      countryName: 'Norfolk Island',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'nf',
    },
    'NCL': {
      countryName: 'New Caledonia',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'nc',
    },
    'MNP': {
      countryName: 'Northern Mariana Islands',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'mp',
    },
    'MHL': {
      countryName: 'Marshall Islands',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'mh',
    },
    'KIR': {
      countryName: 'Kiribati',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'ki',
    },
    'GUM': {
      countryName: 'Guam',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'gu',
    },
    'FSM': {
      countryName: 'Micronesia',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'fm',
    },
    'ASM': {
      countryName: 'American Samoa',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'as',
    },
    'ATF': {
      countryName: 'French Southern Territories',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'tf',
    },
    'COK': {
      countryName: 'Cook Islands',
      fillKey: 'oceania',
      visited: false,
      lived: false,
      flagName: 'ck',
    },

    'ATA': {
      countryName: 'Antarctica',
      fillKey: 'antarctica',
      visited: true,
      lived: false,
      flagName: 'aq',
    },
    'BVT': {
      countryName: 'Bouvet Island',
      fillKey: 'antarctica',
      visited: false,
      lived: false,
      flagName: 'bv',
    },
    'SGS': {
      countryName: 'South Georgia and the South Sandwich Islands',
      fillKey: 'antarctica',
      visited: false,
      lived: false,
      flagName: 'gs',
    },
    'HMD': {
      countryName: 'Heard Island and McDonald Islands',
      fillKey: 'antarctica',
      visited: false,
      lived: false,
      flagName: 'hm',
    },
  };
}
